<?php
if ((!defined('ABS_PATH')))
    exit('ABS_PATH is not loaded. Direct access is not allowed.');
if (!OC_ADMIN)
    exit('User access is not allowed.');
/*
 * Copyright (C) 2016 Puiu Calin
 * This program is a commercial software: is forbidden to use this software without licence, 
 * on multiple installations, and by purchasing from other source than those authorized for the sale of software.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 */
?>
<div id="fb-root"></div>
<script>(function (d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id))
            return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=651333508343077";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
<div class="rights" >
    <a style="float:left;" href="http://theme.calinbehtuk.ro" title="Premium theme and plugins for oslcass">
        <img src="<?php echo osc_base_url() ?>oc-content/plugins/debug/admin/images/calinbehtuk.png" title="premium theme and plugins for oslcass"/></a>
    <span style="float:right;line-height:40px;font-weight:700;"><?php _e('Follow:', 'debug'); ?><a target="blank" style="text-decoration:none;" href="https://www.facebook.com/Calinbehtuk-themes-1086739291344584/"> <img style="margin-bottom:-5px;margin-left:5px;" src="<?php echo osc_base_url() ?>oc-content/plugins/debug/admin/images/facebook.png" title="facebook"/></a></span>
    <div class="like">
        <div class="fb-like" data-href="https://www.facebook.com/Calinbehtuk-themes-1086739291344584/" data-layout="standard" data-action="like" data-show-faces="false" data-share="false"></div>
    </div>
</div>
<div class="debug_area">
    <div class="debug_icon_top"><img src="<?php echo osc_base_url(); ?>oc-content/plugins/debug/images/debug.png"/></div>
    <h2><?php _e('Debug help', 'debug'); ?></h2>
    <div class="help_page"><a href="<?php echo osc_admin_render_plugin_url(osc_plugin_path(dirname(__FILE__)) . '/settings.php'); ?>"><?php _e('Read your debug file', 'debug'); ?></a></div>
    <strong>
        <p><?php _e('Install the plugin.', 'debug'); ?></p>
        <p><center><iframe width="560" height="315" src="https://www.youtube.com/embed/uxNdRXihRg8" frameborder="0" allowfullscreen></iframe></center></p>
        <p><?php _e('This plugin works only if you activate php debug in osclass an save the errors in a debug file.', 'debug'); ?></p>
        <p><?php _e('By activating php debug available in osclass you can read php errors generated by script, theme or plugins on your site. This errors will be save in a file on your server, and you can read the file with a ftp client  or directly from admin osclass by using this plugin.', 'debug'); ?></p>
        <p><?php _e('Bellow you have a tutorial how to activate php debug in osclass and osclass documentation about debug.', 'debug'); ?></p>
    </strong>
    <p><center><iframe width="560" height="315" src="https://www.youtube.com/embed/zmSSJs3hfVA" frameborder="0" allowfullscreen></iframe></center></p>
    <p><a href="https://doc.osclass.org/Debug_PHP_errors"><?php _e('Source Osclass.org', 'debug'); ?></a></p>
    <div class="info">
        <p>The <b>OSC_DEBUG</b> constant, added in version 2.3, controls the display of php errors and warnings. If this setting is not defined in config.php, the default value is false.
        </p><p>When the OSC_DEBUG is false, the error reporting level is E_ALL ^ E_NOTICE ^ E_USER_NOTICE. In that case, we're not showing notice and strict php errors. However, if we set the constant to true, the error reporting level is E_ALL | E_STRICT and display_error value is 1.
        </p><p>The <b>OSC_DEBUG_LOG</b> constant, added in version 2.3, logs these errors to a file called debug.log in oc-content. If Apache doesn't have write permissions, you may need to create the file first and set the appropriate permissions (i.e. use 666). 
        </p>
        <pre>/**
 * Copy this code to config.php file
 * This will disable notice and strict errors
 */
define('OSC_DEBUG', false)&nbsp;;
        </pre>
        <pre>/**
 * Copy this code to config.php file
 * This will show all error notices and warnings on the site
 */
define('OSC_DEBUG', true)&nbsp;;
        </pre>
        <pre>/**
 * Copy this code to config.php file
 * This will log all error notices and warnings to a file called debug.log in oc-content
 */
define('OSC_DEBUG', true)&nbsp;;
define('OSC_DEBUG_LOG', true)&nbsp;;
        </pre>
    </div>
</div>
<?php debug_calinbehtuk_rights(); ?>
<?php debug_other_products(); ?>