<?php
if ((!defined('ABS_PATH')))
    exit('ABS_PATH is not loaded. Direct access is not allowed.');
/*
 * Copyright (C) 2016 Puiu Calin
 * This program is a commercial software: is forbidden to use this software without licence, 
 * on multiple installations, and by purchasing from other source than those authorized for the sale of software.
 * Unauthorized copying of this file, via any medium is strictly prohibited
 */

function premium_off_content_data() {
    $image_url = osc_base_url() . 'oc-content/plugins/premium_off/';
    $style = osc_base_url() . 'oc-content/plugins/premium_off/css/content.css';
    $data = array(
        'info_data' => array(
            'title' => 'Create your own professional site, with premium themes and plugins',
            'image_url' => $image_url,
            'style' => $style
        ),
        '0' => array(
            'title' => 'Premium One Theme',
            'description' => 'Use premium theme one to create a similar site like olx, with a professional design and much more features. Multiple settings and option availeble on this theme and all the updates and improvment are free for life.',
            'link' => 'http://market.osclass.org/themes/general/responsive-one-theme_196',
            'image' => 'images',
            'image_id' => 'one'
        ),
        '1' => array(
            'title' => 'Premium Rita Theme',
            'description' => 'Rita theme allow you to create a goods site, where all your user can sell their products. Professional aspect with a smart selection for category on published page, and all update are free.',
            'link' => 'http://market.osclass.org/themes/general/premium-theme-rita_443',
            'image' => 'images',
            'image_id' => 'rita'
        ),
        '2' => array(
            'title' => 'Premium Calinbehtuk Theme',
            'description' => 'Calinbehtuk a theme with multiple maps, you get to choose one map for free from existing maps. Support is free and the update also.',
            'link' => 'http://market.osclass.org/themes/general/premium-theme-calinbehtuk_493',
            'image' => 'images',
            'image_id' => 'calinbehtuk'
        ),
        '3' => array(
            'title' => 'Premium Ema Theme',
            'description' => 'Ema theme it a ideal theme to use on your site, with two sliders on main page and a professional category selection. All update are free and support related with issues generated by this theme.',
            'link' => 'http://market.osclass.org/themes/premium-osclass-theme-ema_347',
            'image' => 'images',
            'image_id' => 'ema'
        ),
        '4' => array(
            'title' => 'S Message Plugin',
            'description' => 'S Message, a plugin necessary for your site to make the communication easy between your sellers and buyers. No login necessary to read and response to the messages.',
            'link' => 'http://market.osclass.org/plugins/messaging/s-message_532',
            'image' => 'images',
            'image_id' => 'message'
        ),
        '5' => array(
            'title' => 'First One Plugin',
            'description' => 'Allow user to move the ads in top of the list without re publish the ad. User will be notified when the ads can be move on top, the email contains the link for re publish.',
            'link' => 'http://market.osclass.org/plugins/ad-management/first-one-plugin_426',
            'image' => 'images',
            'image_id' => 'first'
        ),
        '6' => array(
            'title' => 'Wishlist Plugin',
            'description' => 'Now visitors can create a wishlist with their favorite items, and for the user with an account on the site, they have option to save the wishlist permanently in his account.',
            'link' => 'http://market.osclass.org/plugins/ad-management/wishlist-plugin_473',
            'image' => 'images',
            'image_id' => 'wishlist'
        ),
        '7' => array(
            'title' => 'Eighteen Plugin',
            'description' => 'Warn the visitor about the content of your site. Display a pop-up on main page, in all pages or in a specific category on search page and item page.',
            'link' => 'http://market.osclass.org/plugins/eighteen-18_281',
            'image' => 'images',
            'image_id' => 'eighteen'
        ),
        '8' => array(
            'title' => 'Floating Social Share',
            'description' => 'Share your site on social networks with a floating share option available on mobile devices also, with professional aspect.',
            'link' => 'http://market.osclass.org/plugins/social-networks/floating-social-share_475',
            'image' => 'images',
            'image_id' => 'floating'
        ),
        '9' => array(
            'title' => 'Sms Payment',
            'description' => 'Make the payment of your premium ads much more easy, just with an sms from your cell phone.',
            'link' => 'http://market.osclass.org/plugins/payments/sms-payment-with-paygol-plugin_481',
            'image' => 'images',
            'image_id' => 'sms'
        ),
        '10' => array(
            'title' => 'Facebook pop-up',
            'description' => 'Display a pop-up with your facebook widget on the first visit, increase the number of likes on your site, with this plugin.',
            'link' => 'http://market.osclass.org/plugins/social-networks/facebook-pop-up_574',
            'image' => 'images',
            'image_id' => 'facebook'
        ),
        '11' => array(
            'title' => 'Premium Phone',
            'description' => 'Now you can add multiple fields for phone, messenger, or skype. Set the order of the fields and display each field individual in your desired area from your page.',
            'link' => 'https://market.osclass.org/plugins/attributes/premium-phone_633',
            'image' => 'images',
            'image_id' => 'premium_phone'
        ),
    );

    return json_encode($data);
}

function premium_off_content() {
    $json = premium_off_content_data();
    $obj = json_decode($json, true);

    $title = $obj['info_data']['title'];
    $image_url = $obj['info_data']['image_url'];
    $style = $obj['info_data']['style'];
    if (!empty($obj)) {
        ?>
        <link rel="stylesheet" href="<?php echo $style; ?>">
        <div class="p_content">
            <h2 class="h_title"><?php echo $title; ?></h2>
            <?php
            unset($obj['info_data']);
            shuffle($obj);
            $obj = array_slice($obj, 0, 5);
            foreach ($obj as $value) {
                ?> 
                <a href="<?php echo $value['link']; ?>" target="blank">
                    <div class="individual_content">
                        <div class="p_image">
                            <img src="<?php echo $image_url; ?>/<?php echo $value['image']; ?>/<?php echo $value['image_id']; ?>.png" title="<?php echo $value['title']; ?>"/>
                        </div>
                        <div class="p_title">
                            <?php echo $value['title']; ?>
                        </div>
                        <div class="p_description">
                            <?php echo $value['description']; ?>
                        </div>
                    </div>
                </a>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.individual_content').hover(function () {
                            $(this).find('.p_description').toggle();
                        });
                    });
                </script>
                <?php
            }
            ?></div><?php
    }
}
